#!/bin/bash
# ------------------------------------------------------------------------------
# Handydandy functions to keep some things DRY
# ------------------------------------------------------------------------------

# linkin is relative from ~/
__linking() {
  if [ -d ~/$1 ] || [ -L ~/$1 ]; then
    if [ ! -L "$HOME/$1" ]; then
      DATE="$(date +%s)"
      mv ~/$1 ~/dotfiles-old/$DATE$1
      __msg "Backup to ~/dotfiles-lod/$DATE$1"
    fi

    if [ -L "$HOME/$1" ] && [ "$(readlink -f ~/$1)" != "$HOME/$2" ]; then
      rm ~/$1
      __msg "Remove outdated link"
    fi

    if [ ! -L "$HOME/$1" ]; then
      ln -s ~/$2 ~/$1
      __msg "Link dotfile"
    fi
  else
    ln -s ~/$2 ~/$1
  fi
  __msg "Done"
}

__header() {
  echo "--------------------------------------------"
  echo "$1"
  echo "--------------------------------------------"
}

__title() {
  echo "\n==== [ $1"
}

__msg() {
  echo "- $1 ✓"
}

__err() {
  echo "- $1 ✖"
}
