#!/bin/bash

# ------------------------------------------------------------------------------
# Handydandy functions to keep some things DRY
# ------------------------------------------------------------------------------

# linkin is relative from ~/
__linking() {
  echo "path: $1"
  echo "dest: $2"
  echo "path_win: $3"

  if [ -e $1 ] || [ -L $1 ]; then

    if [ ! -L "$1" ]; then
      if [ ! -e ~/dotfiles-old ]; then
        __msg "Created ~/dotfiles-old"
        mkdir ~/dotfiles-old
      fi

      DATE="$(date +%s)"

      if [ ! -e ~/dotfiles-old/$DATE ]; then
        __msg "Created ~/dotfiles-old/$DATE"
        mkdir ~/dotfiles-old/$DATE
      fi

      mv $1 ~/dotfiles-old/$DATE$(basename $1)
      __msg "Backup to ~/dotfiles-lod/$DATE$(basename $1)"
    fi

    if [ -L "$1" ] && [ "$(readlink -f $1)" != "$(realpath $2)" ]; then
      rm $1
      __msg "Remove outdated link"
    fi

    if [ ! -L "$1" ]; then
      if [ $3 ] && [ $DOTFILE_CURRENT_OS = "Windows" ]; then
        winln -s $2 $3
        echo 'A'
      else
        ln -s $2 $1
      fi
      __msg "Link dotfile"
    fi
  else
    if [ $3 ] && [ $DOTFILE_CURRENT_OS = "Windows" ]; then
      winln -s $2 $3
    else
      ln -s $2 $1
    fi
  fi
  __msg "Done"
}

__header() {
  echo "--------------------------------------------"
  echo "$1"
  echo "--------------------------------------------"
}

__title() {
  echo ""
  echo "==== [ $1"
}

__msg() {
  echo "- $1 ✓"
}

__err() {
  echo "- $1 ✖"
}
