# ------------------------------------------------------------------------------
# oh-my-zsh configuration
# ------------------------------------------------------------------------------

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# zsh theme
ZSH_THEME="spaceship" #babun
# display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load?
# (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git, cargo, rust, nvm, npm, node)

# ------------------------------------------------------------------------------
# Variables
# ------------------------------------------------------------------------------

DOTFILE_CURRENT_OS="n/a";
case "$(uname -s)" in
  Darwin)
    DOTFILE_CURRENT_OS="OSX"
  ;;

  Linux)
    DOTFILE_CURRENT_OS="Linux"
  ;;

  CYGWIN*|MINGW32*|MSYS*)
    DOTFILE_CURRENT_OS="Windows"
  ;;
esac

# ------------------------------------------------------------------------------
# Paths
# ------------------------------------------------------------------------------

# Base path config
export PATH=$HOME/bin:/usr/local/bin:$PATH

# ------------------------------------------------------------------------------
# Load in
# ------------------------------------------------------------------------------

# get zsh loading
source $ZSH/oh-my-zsh.sh

# add custom configurations
# source $ZSH/custom/example.zsh

# ------------------------------------------------------------------------------
# Custom Aliases
# ------------------------------------------------------------------------------
if [ "$DOTFILES_CURRENT_OS" = "Windows" ]; then
  alias win-Workspace="cd /c/Users/%username%/Workspace/"
  alias win-Home="cd /c/Users/%username%/"
  # yep atom knows about cygwin, but apm not
  alias apm="apm.cmd"
fi

# ------------------------------------------------------------------------------
# Additional fixes mainly for Windows users
# ------------------------------------------------------------------------------

# remove linebreak occuring though cygwin and babun
if [ "$DOTFILES_CURRENT_OS" = "Windows" ]; then
  unsetopt PROMPT_SP
fi
