#!/bin/bash
# ------------------------------------------------------------------------------
# Script to install atom plugins via apm
# ------------------------------------------------------------------------------

if [ ! "$DOTFILE_CURRENT_OS" ]; then
  echo "Please do not call this script directly ... "
  exit 2
fi

# ------------------------------------------------------------------------------
# Install atom and apm
# ------------------------------------------------------------------------------

__header "Component Atom"
__title "Installing"

if [ ! atom ]; then

  if [ "$DOTFILE_CURRENT_OS" = "Mac" ]; then
    brew cask install atom
  fi

  if [ "$DOTFILE_CURRENT_OS" = "Linux" ]; then
    if [ ! -f /etc/apt/sources.list.d/webupd8team-ubuntu-atom-*.list ]; then
      sudo add-apt-repository ppa:webupd8team/atom
      sudo apt update
      sudo apt install atom
    else
    sudo apt install atom
    fi
  fi

  if [ "$DOTFILE_CURRENT_OS" = "Window" ]; then
    choco install atom
  fi
  __msg "Done"
else
  __msg "Already installed"
fi


# ------------------------------------------------------------------------------
# Link files
# ------------------------------------------------------------------------------

__title "Linking"
# linkin is relative from ~/
__linking ".atom" "dotfiles/atom"

# ------------------------------------------------------------------------------
# Install packages
#
# Add all default plugins here, some may require you to add additional files
# so you can add them the the gitignore and this folder.
# ------------------------------------------------------------------------------

__title "Installing Plugins"

apm install\
  gloom\
  project-viewer\
  tool-bar\
  flex-tool-bar\
  language-rust\
  git-log\
  atom-css-comb\
  linter\
  linter-ui-default\
  intentions\
  busy-signal\
  linter-sass-lint\
  linter-jshint\
  linter-jsonlint\
  linter-htmlhint\
  linter-csslint\
  linter-markdown

__msg "Done"
